## ¿Cuál es la diferencia entre `raise` y `throw`? ¿Para qué usarías una u otra opción?


+ `raise` lo que hace es relanzar la excepción que esté almacenada en la variable
global `$!` o un `RuntimeError` si el valor de `$!` es `nil`, siempre y cuando sea
ejecutada sin argumentos.
Si se envía como parámetro el nombre de una excepción de Ruby, entonces será esa
la excepción lanzada. Se puede enviar un segundo parámetro que será el mensaje
asociado a la excepción. También puede haber un tercer parámetro: un arreglo con
información de callback.
```
raise "Failed to create socket"
raise ArgumentError, "No parameters", caller
```

+ `throw` transfiere el control al final de un `catch` que contenga el símbolo
que recibe el `throw` como parámetro. Un segundo parámetro opcional es el valor
que retornará el bloque del `catch`.
En otras palabras, si yo coloco un `throw` dentro de un `catch` y se cumple la
condición que lanza el `throw`, entonces saldré del mismo sin finalizar su ejecución,
ya que, recordemos, el control se dirige al final del `catch`.
Veamos un ejemplo donde queremos agregar palabras dentro de un arreglo y luego
imprimirlo en orden inverso:
```
word_list = File.open("wordlist")
word_in_error = catch(:done) do
    result = []
    while line = word_list.gets
      word = line.chomp
      throw(:done, word) unless word =~ /^\w+$/
      result << word
    end
    puts result.reverse
end
if word_in_error
    puts "Failed: '#{word_in_error}' found. Not a word"
end
```
Aquí vemos claramente que, si se encuentra con que uno de los elementos obtenidos no es
una palabra, deseamos terminar sin imprimir nada. Solo deseamos retornar `nil` aquí.
Esto es muy útil cuando deseamos finalizar sin seguir la ejecución porque algo salió mal a medio camino.
Para esos hijos de puta que no creen en mí.
